Source/ROSIntegration/Private/Conversion/Messages/geometry_msgs/GeometryMsgsQuaternionConverter.cpp
Source/ROSIntegration/Private/Conversion/Messages/geometry_msgs/GeometryMsgsTransformConverter.cpp
Source/ROSIntegration/Private/Conversion/Messages/geometry_msgs/GeometryMsgsTransformStampedConverter.cpp
Source/ROSIntegration/Private/Conversion/Messages/geometry_msgs/GeometryMsgsVector3Converter.cpp

Apparently creating a new bson_t before initializing is enough here.
Please mind that I have no experience with BSON, so this might not be the intended solution. A quick test showed that I can now send geometry messages without problems though.
This would fix issue #20

Fix crash on publishing GeometryMsg.

---

README.md
Source/ROSIntegration/ROSIntegration.Build.cs

**UE 4.19.2** and **Visual Studio 2015** create an error while generating the Visual Studio Solution, because of the keyword ```Definitions``` in Source/ROSIntegration/ROSIntegration.Build.cs.
The keyword ```PublicDefinitions``` ist tested sucessfully with 4.18.3 and 4.19.2. It definitly does not work with 4.16.3 and 4.17.2. That's why I added the macro **UE_4_19_OR_LATER**.

Build.cs: Definitions -> PublicDefinitions

---

Source/ROSIntegration/Private/Conversion/Messages/sensor_msgs/SensorMsgsImageConverter.h

due to the 'data'-field in sensor_msgs/Image being removed.
I think we should discuss whether it's a good idea to diverge from the naming of fields in the original message definition. We have no field "data" in this message anymore, only the data_ptr. Imho we should either call the data_ptr "data" now or reintroduce the data-field as a TArray. What was the reason to remove the TArray data in the first place? As far as I know it doesn't really impact speed or memory when handled correctly.

Last commit introduced a compiler error

---

Source/ROSIntegration/Private/Conversion/Messages/BaseMessageConverter.h
Source/ROSIntegration/Private/Conversion/Messages/nav_msgs/NavMsgsMapMetaDataConverter.cpp
Source/ROSIntegration/Private/Conversion/Messages/nav_msgs/NavMsgsMapMetaDataConverter.h
Source/ROSIntegration/Private/Conversion/Messages/nav_msgs/NavMsgsOccupancyGridConverter.cpp
Source/ROSIntegration/Private/Conversion/Messages/nav_msgs/NavMsgsOccupancyGridConverter.h
Source/ROSIntegration/Public/nav_msgs/MapMetaData.h
Source/ROSIntegration/Public/nav_msgs/OccupancyGrid.h

Please review the proposed additions. They add support for bson conversion of int arrays as well as two standard messages: nav_msgs/MapMetaData and nav_msgs/OccupancyGrid.
I've tested these against UE4.20 with ros melodic and successfully passed the messages both directions. For the project I am working on, I may have other standard messages I will need to add. If you add me to the main repository, I would prefer to push the additions to a branch there instead of a fork.

Add support for 2 standard nav_msgs

---

Source/ROSIntegration/Private/Conversion/Messages/BaseMessageConverter.h

to prevent errors for past-the-end reading as suggested in #66.

Adjust the parsing of arrays

---

Source/ROSIntegration/Private/Conversion/Messages/actionlib_msgs/ActionlibMsgsGoalIDConverter.h
Source/ROSIntegration/Private/Conversion/Messages/actionlib_msgs/ActionlibMsgsGoalStatusArrayConverter.h
Source/ROSIntegration/Private/Conversion/Messages/actionlib_msgs/ActionlibMsgsGoalStatusConverter.h
Source/ROSIntegration/Private/Conversion/Messages/geometry_msgs/GeometryMsgsPointConverter.h
Source/ROSIntegration/Private/Conversion/Messages/geometry_msgs/GeometryMsgsPoseConverter.h
Source/ROSIntegration/Private/Conversion/Messages/geometry_msgs/GeometryMsgsPoseStampedConverter.h
Source/ROSIntegration/Private/Conversion/Messages/geometry_msgs/GeometryMsgsPoseWithCovarianceConverter.h
Source/ROSIntegration/Private/Conversion/Messages/geometry_msgs/GeometryMsgsQuaternionConverter.h
Source/ROSIntegration/Private/Conversion/Messages/geometry_msgs/GeometryMsgsTransformConverter.h
Source/ROSIntegration/Private/Conversion/Messages/geometry_msgs/GeometryMsgsTwistConverter.h
Source/ROSIntegration/Private/Conversion/Messages/geometry_msgs/GeometryMsgsTwistWithCovarianceConverter.h
Source/ROSIntegration/Private/Conversion/Messages/geometry_msgs/GeometryMsgsVector3Converter.h
Source/ROSIntegration/Private/Conversion/Messages/grid_map_msgs/GridMapMsgsGridMapConverter.h
Source/ROSIntegration/Private/Conversion/Messages/grid_map_msgs/GridMapMsgsGridMapInfoConverter.h
Source/ROSIntegration/Private/Conversion/Messages/nav_msgs/NavMsgsMapMetaDataConverter.h
Source/ROSIntegration/Private/Conversion/Messages/sensor_msgs/SensorMsgsLaserScanConverter.h
Source/ROSIntegration/Private/Conversion/Messages/std_msgs/StdMsgsFloat32MultiArrayConverter.h
Source/ROSIntegration/Private/Conversion/Messages/std_msgs/StdMsgsHeaderConverter.h
Source/ROSIntegration/Private/Conversion/Messages/std_msgs/StdMsgsMultiArrayDimensionConverter.h
Source/ROSIntegration/Private/Conversion/Messages/std_msgs/StdMsgsMultiArrayLayoutConverter.h
Source/ROSIntegration/Private/Conversion/Messages/std_msgs/StdMsgsUInt8MultiArrayConverter.h

I wanted to implement some new message, which contain arrays of existing messages, but because of the missing const modifier I was not allowed to.

Add const to ROSMessage pointer in _bson_append_... to make them usable for _bson_append_tarray

---

Source/ROSIntegration/Private/Conversion/Messages/nav_msgs/NavMsgsPathConverter.cpp

BSON converter for `nav_msgs/Path` was missing `'msg'` in the key name which would cause the converter to fail.

fix key name in NavMsgsPathConverter

---

Source/ROSIntegration/Private/ROSIntegrationGameInstance.cpp

Only update simulation time if the UE tick is of time type. See issue #75 it goes into detail about the issues, read the last comment by me in which I detail what this fixes/does.

Fix double tick clock advance.

---

Source/ROSIntegration/Private/rosbridge2cpp/TCPConnection.cpp

When the TCP connection to ROS is lost, the comm thread locks causing the Unreal Editor to subsequently lock-up.
Setting `run_receiver_thread` to `false` when this occurs allows the TCP connection to close and re-establish correctly when ROS communication is re-established.
The log statement is also updated to notify the thread will be closed.

Fix for TCP thread locking when ROS Connection is lost

---

Source/ROSIntegration/Classes/ROSIntegrationGameInstance.h
Source/ROSIntegration/Private/ROSIntegrationGameInstance.cpp

UE 4.24 appears to change the [FOnWorldTickStart](https://docs.unrealengine.com/en-US/API/Runtime/Engine/Engine/FWorldDelegates/FOnWorldTickStart/index.html) definition for [FWorldDelegates](https://docs.unrealengine.com/en-US/API/Runtime/Engine/Engine/FWorldDelegates/index.html) adding a pointer to `UWorld`.
~~This may break compatibility with versions prior to 4.24, but without it the plugin will not build for 
UE 4.24.~~
Please let me know your thoughts,
Tim
`ENGINE_MINOR_VERSION` is now used to handle the `OnWorldTickStart` definition in order to support prior versions of UE4.

UE 4.24 OnWorldTickStart Definition Change

---

Source/ROSIntegration/Private/Topic.cpp

- Removes the check assertion call inside UTopics internal implementation 
- Updates UE_LOG error to make empty Topic names / Message types easier to read

Fix crash when Topic & Message Type are unrecognized

---

Config/FilterPlugin.ini
README.md
ROSIntegration.uplugin
Source/ROSIntegration/Classes/SpawnableObject.h
Source/ROSIntegration/Classes/TFBroadcastComponent.h
Source/ROSIntegration/Private/Conversion/Messages/BaseMessageConverter.h
Source/ROSIntegration/Private/rosbridge2cpp/TCPConnection.cpp
Source/ROSIntegration/Public/ROSIntegration.h
Source/ROSIntegration/ROSIntegration.Build.cs

This PR sets the Plugin to an 'Installed' plugin.
- `Config/FilterPlugin.ini` for linking libbson binaries
- CanContainContent since this plugin does not have a Content directory
- Slate dependencies 
The following were errors generated by the RunUAT tool when compiling the plugin by itself.
- Add missing category tags to uproperties
- Add `Public` directory to `PublicIncludePaths` and remove its usage inside `BaseMessageConverter`
- Fix `ModuleManager` include path
- Removes monolithic import of `Networking.h`
Readme updated with information regarding the installed plugin.
Note:  the plugin may still be used in the previous manner (setting Modules, AdditionalDependencies in the uproject) and UE will ask to rebuild it if it is not yet built by a project using it.

Installable Plugin

---

Source/ROSIntegration/Private/Conversion/Messages/std_msgs/StdMsgsHeaderConverter.h

A compiler error is generated when referencing `_bson_append_header`
```bash
[...]/ROSIntegration/Source/ROSIntegration/Private/Conversion/Messages/actionlib_msgs/ActionlibMsgsGoalStatusArrayConverter.h:48:51: error: cannot initialize a parameter of type 'ROSMessages::std_msgs::Header *' with an rvalue of type 'const std_msgs::Header *'
```
Add `const` to header param in `_bson_append_header`

Fix BSON Append Header Const Correctness

---

Source/ROSIntegration/Private/Topic.cpp

If someone calls `Unadvertise` / or `Advertise` before `Init` on a topic, the check assertion will cause the Editor / Game to crash.
Instead of using an assert, I recommend logging a warning to tell the user to initialize their topic first.

Fix Topic Advertise / Unadvertise Assertions

---

Source/ROSIntegration/Private/Conversion/Messages/geometry_msgs/GeometryMsgsTransformStampedConverter.h

When I build plugin, I got this error.
So I change header file path.
Please review this code.
Test Env Ubuntu 18.04 / UE 2.24.3

Fix header path TransformStamped.h -> geometry_msgs/TransformStamped.h

---

Source/ROSIntegration/Private/rosbridge2cpp/TCPConnection.cpp

`IPAddress.h` includes the definition for `FInternetAddr`, which is returned by the `CreateInternetAddr()` function used in `TCPConnection.cpp`. It was not included after the removal of the monolithic header in #108, and therefore compilation failed.
I have not tested on later versions of the engine as I have only 4.20.3 installed on my machine. I can't imagine this would break on later versions of the engine since I just added an extra include. I guess I'm just surprised that it does compile on later versions. Perhaps they included this header in one of the other already-included headers for later versions? No idea. Or maybe it was just a mistake :)

Fixed compilation on UE 4.20.3

---

ThirdParty/bson/include/windows/bson-compat.h

Relates to and Closes #114 
Fixes the WinSock2 include inside `windows/bson-compat` as it has a naming collision with UE4's TEXT macro. 
Verified with 4.25.3

WinSock2 Include Fix

---

Source/ROSIntegration/Classes/ROSIntegrationGameInstance.h

I had the need to make my own game instance and override the behavior of clock topic published by the `ROSIntegrationGameInstance.`
Changes:
- Added virtual to `OnWorldTickStart` to make it possible for children to override it
- Changed `ClockTopic` from private to protected to make it accessible by children
Results:
Tested on UE 4.25.3 and no behavior change is introduced. I created my own GameInstance which inherits the `ROSIntegrationGameInstance` and I was able to change the clock behavior (manually advance sim time when needed instead of sync with UE frame advance).

Add the ability to override and access clock related methods in ROSIntegrationGameInstance

---

Source/ROSIntegration/Private/Topic.cpp

**What this PR does**
This PR solves issue that result in fatal errors (immediate crashed upon launching of a packaged project) due to usage of blueprint topics. 
**Problem**
Blueprint topics are relying on 'OnConstruct()' function found in the Topic.cpp class. They are initialized in the virtual function PostInitProperties().
PortInitProperties is currently called upon initial loading of internal classes, and when an Ubject is created/spawned in the world. For our use case of Topic creation, we are expecting this to occur when blueprint Topics are created in the world. However since we were not explicitely checking for this, 'OnConstruct()' was called way earlier than expected, and causing errors that resulted in the application crashing. Please refer to the following issue for more …

Fix for crash of package projects using blueprint topics

---

Source/ROSIntegration/Private/ROSIntegrationGameInstance.cpp

There was a problem in the scenario with high frequency subscription messages. If a message arrived after UROSIntegrationGameInstance::Shutdown(), it would try to trigger an invocation of a subscription callback during an unsafe topic state, causing a crash (not in the callback implementation, but in ROSIntegration).  Therefore, unsubribe all topics in beginning of shutdown to ignore messages arriving after.
Also, at the same moment, unadvertise all topics.

Fix to avoid potential shutdown crash

---

Source/ROSIntegration/Classes/RI/Topic.h
Source/ROSIntegration/Private/Conversion/Messages/std_msgs/StdMsgsEmptyConverter.cpp
Source/ROSIntegration/Private/Conversion/Messages/std_msgs/StdMsgsEmptyConverter.h
Source/ROSIntegration/Private/Conversion/Messages/std_msgs/StdMsgsInt64Converter.cpp
Source/ROSIntegration/Private/Conversion/Messages/std_msgs/StdMsgsInt64Converter.h
Source/ROSIntegration/Private/Topic.cpp
Source/ROSIntegration/Public/std_msgs/Empty.h
Source/ROSIntegration/Public/std_msgs/Int64.h

I have implemented more of the BP features.
I will do more. But this is what I need for the moment.

Adding more BP topic types

---

Source/ROSIntegration/Classes/ROSIntegrationGameInstance.h
Source/ROSIntegration/Private/ROSIntegrationGameInstance.cpp
Source/ROSIntegration/Private/ROSTime.cpp
Source/ROSIntegration/Private/rosbridge2cpp/TCPConnection.cpp
Source/ROSIntegration/Public/ROSTime.h

I meant to submit this PR a while ago but didn't get around to it. I fixed some outstanding bugs and added a few features I think are quite useful.
1. When the game instance disconnects from rosbridge and then reconnects (without stopping the game), the ROSIntegrationGameInstance would re-add the same function to the global OnWorldTickStart() function, and consequently the ROSTime would advance at a faster rate. Every time it would try to reconnect it would keep adding this function, making the problem worse. I added a boolean check to ensure it only gets added once.
2. I added some nullptr checks when trying to send data over TCP. Occasionally nullptr messages would get sent when the game is stopped and then the game would freeze up.
3. I updated the auto-shutdown feature from …

Fixed ROSTime Advancement Issue, Added Nullptr Checks, Autoshutdown ROS Objects, Added New Features

---

Config/Engine.ini
Source/ROSIntegration/Classes/ROSBridgeParamOverride.h
Source/ROSIntegration/Classes/ROSIntegrationCore.h
Source/ROSIntegration/Classes/ROSIntegrationGameInstance.h
Source/ROSIntegration/Private/ROSIntegrationCore.cpp
Source/ROSIntegration/Private/ROSIntegrationGameInstance.cpp
Source/ROSIntegration/Private/Service.cpp
Source/ROSIntegration/Private/Topic.cpp
Source/ROSIntegration/Private/rosbridge2cpp/WebsocketConnection.cpp
Source/ROSIntegration/Private/rosbridge2cpp/WebsocketConnection.h
Source/ROSIntegration/ROSIntegration.Build.cs

* Added WebsocketConnection object.
* Added LWS parameters to engine.ini (otherwise websocket messages get throttled to 30hz)
* Changed UImpl to have a rosbridge2cpp::ROSBridge pointer and updated all references.
* Added ROSBridgeServerProtocol variable to UROSIntegrationGameInstance & AROSBridgeParamOverride
* Changed the Init() function call chain to pass protocol variable along
Tested on UE4 4.27, ROS1 Melodic (Python 2) on Ubuntu 18.04, using rosbridge_suite 0.11.10
Note: websocket_external_port must be set on the rosbridge server: `roslaunch rosbridge_server rosbridge_websocket.launch websocket_external_port:=80`

Added Websocket Support

---

Source/ROSIntegration/Private/rosbridge2cpp/itransport_layer.h

fixes "error: delete called on non-final 'TCPConnection' that has virtual functions but non-virtual" when building for UE 5.2

Add Virtual deconstructor for ITransportLayer in itransport_layer.h

---

Source/ROSIntegration/Private/rosbridge2cpp/TCPConnection.cpp

There was a problem that in some environments, after a random time of play (usually a minute or so) the subscription message processing suddenly failed and could not recover. 
After investigation, it turns out that this happened if the message header (the first 4 bytes for the message length) arrived in multiple packets, i.e. it could not be read by only one *_sock->Recv()* instruction. In this case the error message *"bytes_read is not 4 in bson_state_read_length==true."* would display and from there on no further message processing can be done.
Fixed this by allowing reading of the header multiple times until all 4 bytes have been read.

Fix to avoid bug when reading subscription message header

---

Source/ROSIntegration/Private/Conversion/Messages/tf2_msgs/Tf2MsgsTFMessageConverter.cpp

Fixes creating outgoing TF2 message. 
Previously it was initialized to a nullptr, this is necessary, to send these types of messages.

bugfix: initialize tf2 bson message

---

README.md

This one line change PR allows for building on UE5.
Tracking issue here: https://github.com/code-iai/ROSIntegration/issues/208
This has been tested on UE5 + Linux

Allows building on UE5
